#Kibana API URL endpoint
KIBANA_HTTP_URL_ENDPOINT: 'https://kibana.bla'
# Kibana http authorization base64encoded: user:pass
KIBANA_HTTP_BASIC_AUTH: 'blabla'
#Kibana Index prefix
KIBANA_INDEX_PREFIX: 'index-app-'
# Kibana search key used on counter
KIBANA_ROUTING_KEY: 'routing.key.used.on.searchquery'
# Kibana search key used search cancel by timeout and the vins
KIBANA_VEHICLES_ROUTING_KEY: 'mda.v1'
KIBANA_VEHICLE_INDEX_PREFIX: 'blabla-app-' 